export const games = [
  {
    home: 'Czarni Sosnowiec 18',
    away: 'GKS Katowice',
    scoreAway: 2,
    scoreHome: 2,
    date: '9/17/18 1:21',
    round: 2,
    league: 'Ekstraliga',
    season: '2020/2021',
    isFinished: true,
  },
  {
    home: 'Czarni Sosnowiec 16',
    away: 'GKS Katowice frss',
    scoreAway: 2,
    scoreHome: 2,
    date: '9/17/16 1:21',
    round: 2,
    league: 'Ekstraliga',
    season: '2020/2021',
    isFinished: true,
  },
  {
    home: 'Czarni Sosnowiec 17',
    away: 'GKS Katowice',
    scoreAway: 2,
    scoreHome: 2,
    date: '9/17/17 1:21',
    round: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
    isFinished: true,
  },
  {
    home: 'Czarni Sosnowiec',
    away: 'GKS Katowice',
    scoreAway: 2,
    scoreHome: 2,
    date: '9/17/16 1:21',
    round: 2,
    league: 'Ekstraliga',
    season: '2020/2021',
    isFinished: true,
  },
  {
    home: 'Czarni Sosnowiec',
    away: 'GKS Katowice',
    scoreAway: 2,
    scoreHome: 2,
    date: '9/17/16 1:21',
    round: 1,
    league: 'Ekstraliga',
    season: '2020/2021',
    isFinished: true,
  },
  {
    home: 'Czarni Sosnowiec',
    away: 'GKS Katowice',
    scoreAway: 2,
    scoreHome: 2,
    date: '9/17/16 1:21',
    round: 10,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
];
