export const goals = [
  {
    name: 'Patrycja Trzcińska',
    league: 'Ekstraliga',
    season: '2020/2021',
    game: 12,
    goals: 2,
    club: 'LFA Szczecin',
  },
  {
    name: 'Patrycja Trzcińska',
    league: 'Ekstraliga',
    season: '2020/2021',
    game: 12,
    goals: 5,
    club: 'LFA Szczecin',
  },
  {
    name: 'Marianna Litwiniec',
    league: 'Ekstraliga',
    season: '2020/2021',
    game: 12,
    goals: 1,
    club: 'Górnik Łęczna',
  },
  {
    name: 'Marianna Litwiniec',
    league: 'Ekstraliga',
    season: '2020/2021',
    game: 1,
    goals: 2,
    club: 'Górnik Łęczna',
  },
  {
    name: 'name2',
    league: 'Ekstraliga',
    season: '2020/2021',
    game: 1,
    goals: 5,
    club: 'Górnik Łęczna',
  },
  {
    name: 'name1',
    league: 'Ekstraliga',
    season: '2020/2021',
    game: 1,
    goals: 2,
    club: 'Górnik Łęczna',
  },
  {
    name: 'name1',
    league: 'Ekstraliga',
    season: '2020/2021',
    game: 1,
    goals: 1,
    club: 'Górnik Łęczna',
  },
];
