export const table = [
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 15,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 6,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 1,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
  {
    name: 'GKS Katowice',
    gamesPlayed: 3,
    won: 2,
    draw: 1,
    lost: 0,
    goalDiff: 5,
    points: 5,
    league: 'Ekstraliga',
    season: '2020/2021',
  },
];
